name: Terraform

on:
  push:
    branches:
      - main  # or the branch you want to trigger the workflow

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.0.11  # Specify your Terraform version here

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Specify your AWS region here

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -destroy

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'  # Apply only on the main branch
        run: terraform apply -auto-approve
